"""add audio-user-relationship

Revision ID: d68ac22d0576
Revises: caad09cc7388
Create Date: 2025-03-30 08:09:50.239612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd68ac22d0576'
down_revision: Union[str, None] = 'caad09cc7388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_files', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'audio_files', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audio_files', type_='foreignkey')
    op.drop_column('audio_files', 'user_id')
    # ### end Alembic commands ###
