version: "3.9"
services:
  db:
    image: postgres:16-alpine3.20
    container_name: postgres
    restart: always

    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .db.env
    ports:
      - "5432:5432"

volumes:
  db-data:
